studies/master/urls.py
from django.urls import path

from . import views
from .views import (
    CourseCreateView,
    CourseTypeCreateView,
    SpecializationCreateView,
    StudentCourseCreateView,
    StudentCourseDeleteView,
    StudentCourseUpdateView,
    UpdateStudent,
)

urlpatterns = [
    path("", views.overview, name="overview"),
    path("semesterview", views.semesters, name="semester-view"),
    # /master/course/5/
    path(
        "studentcourse/<int:course_id>",
        views.studentcourse_detail,
        name="studentcourse-detail",
    ),
    path(
        "studentcourse/new/",
        StudentCourseCreateView.as_view(),
        name="studentcourse-create",
    ),
    path(
        "studentcourse/<int:course_id>/confirm",
        views.confirm_studentcourse,
        name="studentcourse-confirm",
    ),
    path(
        "studentcourse/<int:pk>/update",
        StudentCourseUpdateView.as_view(),
        name="studentcourse-update",
    ),
    path(
        "studentcourse/<int:pk>/delete",
        StudentCourseDeleteView.as_view(),
        name="studentcourse-delete",
    ),
    path("student/", views.student_view, name="student"),
    path("student/<int:pk>/update", UpdateStudent.as_view(), name="student-update"),
    path("course/new", CourseCreateView.as_view(), name="course-create"),
    path(
        "specialization/new",
        SpecializationCreateView.as_view(),
        name="specialization-create",
    ),
    path("type/new", CourseTypeCreateView.as_view(), name="type-create"),
    path("exams", views.exam_date_view, name="exam-dates"),
]

studies/studies/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path("", include("master.urls")),
    path("admin/", admin.site.urls),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="master/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="master/logout.html"),
        name="logout",
    ),
]

studies/master/models.py
from math import floor
from decimal import Decimal, ROUND_FLOOR
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.shortcuts import get_object_or_404
from django.urls import reverse


MAX_CREDITS_SEM_INT = 18


# The specializations for a course (Vertiefungsfächer)
class Specialization(models.Model):
    specialization_name = models.CharField(
        max_length=100, unique=True, verbose_name="Name"
    )
    specialization_abbreviation = models.CharField(
        max_length=10, unique=True, verbose_name="Abkürzung"
    )

    def __str__(self):
        return self.specialization_name

    def get_absolute_url(self):
        return reverse("overview")

    def get_courses(self, student):
        return (
            StudentCourse.objects.all()
            .filter(course__specializations__contains=self)
            .filter(student=student)
        )

    def get_sum_of_credits(self, student):
        return sum(c.credit_points for c in self.get_courses(student))


# Custom User Model Student
# regular user model extended with major1 and major2
class Student(AbstractUser):
    major1 = models.ForeignKey(
        Specialization,
        blank=True,
        null=True,
        default=None,
        on_delete=models.SET_NULL,
        verbose_name="Vertiefungsfach 1",
        related_name="major1",
    )
    major2 = models.ForeignKey(
        Specialization,
        blank=True,
        null=True,
        default=None,
        on_delete=models.SET_NULL,
        verbose_name="Vertiefungsfach 2",
        related_name="major2",
    )

    def __str__(self):
        return self.username


# The type of a course
class CourseType(models.Model):
    type_name = models.CharField(max_length=30, unique=True, verbose_name="Name")
    type_abbreviation = models.CharField(
        max_length=5, unique=True, verbose_name="Abkürzung"
    )
    min_ects_required = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="Minimal nötige Anzahl ECTS in dieser Kategorie",
    )
    max_ects_creditable = models.IntegerField(
        blank=True, null=True, verbose_name="Maximale Anzahl anrechenbarer ECTS"
    )

    def __str__(self):
        return self.type_abbreviation

    def get_absolute_url(self):
        return reverse("overview")

    def get_courses(self, student):
        return (
            StudentCourse.objects.all()
            .filter(course__course_type=self)
            .filter(student=student)
        )

    def get_included_courses(self, student):
        return (
            StudentCourse.objects.all()
            .filter(course__course_type=self)
            .filter(included=True)
            .filter(student=student)
        )

    def get_sum_of_credits(self, student):
        total = sum(c.course.credit_points for c in self.get_included_courses(student))
        return (
            min(self.max_ects_creditable, total) if self.max_ects_creditable else total
        )

    def get_missing_credits(self, student):
        if not self.min_ects_required:
            return -1
        return max(0, self.min_ects_required - self.get_sum_of_credits(student))

    def get_possible_credits(self, student):
        if not self.max_ects_creditable:
            return -1
        return max(0, self.max_ects_creditable - self.get_sum_of_credits(student))

    def is_valid(self, student):
        return self.get_missing_credits(student) == 0

    def get_average(self, student):
        credits_grades = [
            (c.course.credit_points, c.grade)
            for c in self.get_included_courses(student)
            if c.grade > 0
        ]
        if not credits_grades:
            return 0.0

        ects, grades = zip(*credits_grades)

        if not ects or not grades:
            return 0.0

        credits_averages = [ects[i] * grades[i] for i in range(len(ects))]

        avg = sum(credits_averages) / sum(ects)
        return avg.quantize(Decimal(".0001"), rounding=ROUND_FLOOR)


# The course itself
class Course(models.Model):
    course_name = models.CharField(max_length=200, verbose_name="Titel")
    credit_points = models.DecimalField(
        max_digits=3, decimal_places=1, default=0, verbose_name="ECTS"
    )
    course_type = models.ForeignKey(
        CourseType,
        on_delete=models.SET_NULL,
        default=None,
        null=True,
        verbose_name="Kurstyp",
    )
    specializations = models.ManyToManyField(
        Specialization, blank=True, verbose_name="Vertiefungsfächer laut Modulhandbuch"
    )

    def __str__(self):
        return self.course_name

    def get_credits(self):
        return min(self.category.max_ects_creditable, self.credit_points)

    def get_absolute_url(self):
        return reverse("studentcourse-detail", kwargs={"course_id": self.pk})

    def get_specializations_abbreviations(self):
        l = [c.specialization_abbreviation for c in self.specializations.all()]
        return ", ".join(l)


class Category(models.Model):
    category_name = models.CharField(
        max_length=100, unique=True, verbose_name="Studienteil"
    )
    min_ects_required = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="Minimal nötige Anzahl ECTS in diesem Bereich",
    )
    max_ects_creditable = models.IntegerField(
        blank=True, null=True, verbose_name="Maximale Anzahl anrechenbarer ECTS"
    )

    def __str__(self):
        return self.category_name

    def get_courses(self, student):
        return self.studentcourse_set.all().filter(student=student)

    def get_included_courses(self, student):
        return (
            self.studentcourse_set.all().filter(included=True).filter(student=student)
        )

    def get_included_courses_with_grade(self, student):
        return (
            self.studentcourse_set.all()
            .filter(grade__gt=0)
            .filter(included=True)
            .filter(student=student)
        )

    def get_sum_of_credits_with_grade(self, student):
        total = sum(
            c.course.credit_points
            for c in self.get_included_courses_with_grade(student)
        )
        return (
            min(self.max_ects_creditable, total) if self.max_ects_creditable else total
        )

    def get_sum_of_credits(self, student):
        total = sum(c.course.credit_points for c in self.get_included_courses(student))
        return (
            min(self.max_ects_creditable, total) if self.max_ects_creditable else total
        )

    def get_missing_credits(self, student):
        if not self.min_ects_required:
            return 0
        return max(0, self.min_ects_required - self.get_sum_of_credits(student))

    def get_possible_credits(self, student):
        if not self.max_ects_creditable:
            return -1
        return max(0, self.max_ects_creditable - self.get_sum_of_credits(student))

    def is_valid(self, student):
        return self.get_missing_credits(student) == 0

    def get_average(self, student):
        credits_grades = [
            (c.course.credit_points, c.grade)
            for c in self.get_included_courses(student)
            if c.grade > 0
        ]
        if not credits_grades:
            return Decimal(0)

        ects, grades = zip(*credits_grades)

        if not ects or not grades:
            return Decimal(0)

        credits_averages = [ects[i] * grades[i] for i in range(len(ects))]

        avg = sum(credits_averages) / sum(ects)
        return avg.quantize(Decimal(".0001"), rounding=ROUND_FLOOR)

    def get_kit_average(self, student):
        avg = self.get_average(student)
        return avg.quantize(Decimal(".1"), rounding=ROUND_FLOOR)


class Semester(models.Model):
    # SS20 oder WS19/20
    term = models.CharField(
        max_length=2, choices=[("SS", "Sommersemester"), ("WS", "Wintersemester")]
    )
    year = models.CharField(max_length=5)

    def __str__(self):
        return self.term + " " + self.year

    def get_courses(self, student):
        return (
            self.studentcourse_set.all().filter(student=student).order_by("exam_date")
        )

    def get_included_courses(self, student):
        return (
            self.studentcourse_set.all().filter(included=True).filter(student=student)
        )

    def get_sum_of_credits(self, student):
        return sum(c.course.credit_points for c in self.get_included_courses(student))

    def get_average(self, student):
        credits_grades = [
            (c.course.credit_points, c.grade)
            for c in self.get_included_courses(student)
            if c.grade > 0
        ]
        if not credits_grades:
            return 0.0

        ects, grades = zip(*credits_grades)

        credits_averages = [ects[i] * grades[i] for i in range(len(ects))]

        avg = sum(credits_averages) / sum(ects)
        return avg.quantize(Decimal(".0001"), rounding=ROUND_FLOOR)


class StudentCourse(models.Model):
    student = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Student"
    )
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="Kurs")
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        null=False,
        verbose_name="Kategorie",
    )
    semester = models.ForeignKey(
        Semester,
        on_delete=models.CASCADE,
        null=False,
        verbose_name="Prüfungssemester",
    )
    exam_date = models.DateTimeField(
        verbose_name="Prüfungstermin", blank=True, null=True
    )
    grade = models.DecimalField(
        max_digits=2,
        decimal_places=1,
        blank=True,
        null=True,
        default=0,
        verbose_name="Note",
    )
    included = models.BooleanField(
        default=True, verbose_name="In Berechnung mit einbeziehen?"
    )

    def __str__(self):
        return f"{self.course} ({self.student})"


def get_total_credits(student):

studies/master/forms.py
from bootstrap_datepicker_plus import DateTimePickerInput
from django import forms
from django.urls import reverse_lazy
from django_addanother.widgets import AddAnotherWidgetWrapper

from .models import StudentCourse


class StudentCourseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.use_required_attribute = False

    class Meta:
        model = StudentCourse
        exclude = ["student"]
        widgets = {
            "course": AddAnotherWidgetWrapper(
                forms.Select(
                    attrs={
                        "class": "selectpicker",
                        "data-live-search": "true",
                        "data-size": "5",
                    },
                ),
                reverse_lazy("course-create"),
            ),
            "exam_date": DateTimePickerInput(format="%Y-%m-%d %H:%M"),
            "category": forms.Select(
                attrs={"class": "selectpicker", "data-live-search": "true",}
            ),
            "semester": forms.Select(
                attrs={"class": "selectpicker", "data-live-search": "true",}
            ),
        }

studies/master/templates/master/base.html
{% load static %}
{% load fontawesome_5 %}
{% load activeurl %}

<!doctype html>
<html lang="de">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <!-- Bootstrap-select CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
  <!-- Custom CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'master/main.css' %}"/>
  <!-- Load jQuery first because django is stupid (required so popups in forms work) -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  {% fontawesome_5_static %} 
  <title>Master @ KIT</title>
</head>

<body>
{% activeurl %}
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'overview' %}"><img src={% static 'master/KIT_Logo.png' %} width="auto" height="40" alt=""></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link nav-link-studies" href="{% url 'overview' %}">Übersicht</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'semester-view' %}">Semesteransicht</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'exam-dates' %}">Prüfungstermine</a>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'studentcourse-create' %}"><i class="fas fa-plus-circle"></i> Kurs</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'student' %}">Profil</a>
                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
    </div>
  </nav>
{% endactiveurl %}
  <main role="main" class="container">

    {% if messages %} 
    {% for msg in messages %}
      <div class="alert alert-{{ msg.tags }}">
      {{ msg }}
      {% endfor %} 
    {% endif %} 
      
    {% block content %}
    {% endblock %}
    </div>
  </main>
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <!-- Bootstrap-select Javascript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>

  {% block javascript %}
  {% endblock javascript %}
</body>
</html>

studies/master/templates/master/category_form.html
{% extends "master/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST">
{% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Neues Vertiefungsfach</legend>
        {{ form|crispy }}
    </fieldset>
        <button class="btn btn-outline-info" type="submit">Speichern</button>
</form>
{% endblock content %}

studies/master/templates/master/confirm_course.html
{% extends 'master/base.html' %}
{% block content %}
<div>
    <p>Das {{ course.course_type }} das du hinzufügen möchtest ist nicht mehr anrechenbar, da bereits 18 ECTS im Bereich
        Seminare und Praktika verrechnet sind.</p>
    <p>Möchtest du {{ course.course_name }} dennoch zu deinem Studium hinzufügen?</p>
    <p>Das {{ course.course_type }} wird dann nicht in die Anzahl ECTS und Durschnittsnote miteinberechnet.</p>
    <p>Du kannst die Auswahl der angerechneten Kurse auch später noch ändern.</p>
    <form method="POST" action="{% url 'course-delete' course.pk%}">
        {% csrf_token %}
        <button class="btn btn-outline-info" type="sumbit">Nein, löschen</button>
    </form>
    <form method="POST" action="">
        {% csrf_token %}
        <button class="btn btn-outline-info" type="submit">Ja, hinzufügen</button>
    </form>
</div>
{% endblock content %}

studies/master/templates/master/course_confirm_delete.html
{% extends "master/base.html" %} 
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Kurs löschen</legend>
            <h2>Bist du sicher, dass du den Kurs {{ object.course_name }} löschen willst?</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Ja, löschen</button>
            <a class="btn btn-outline-secondary" href="{% url 'course-detail' object.pk %}">Abbrechen</a>
        </div>
    </form>
</div>
{% endblock content %}

studies/master/templates/master/course_form.html
{% extends "master/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST">
{% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Neuen Kurs anlegen.</legend>
        {{ form|crispy }}
    </fieldset>
        <button class="btn btn-outline-info" type="submit">Speichern</button>
</form>
{% endblock content %}

studies/master/templates/master/course_table.html
<div class="table-responsive">

    <table class="table">
        <tr>
            <th>Kursname</th>
            <th>ECTS</th>
            <th>Kurstyp</th>
            <th>mögliche Vertiefungsfächer</th>
            <th>Prüfungssemester</th>
            <th>Prüfungstermin</th>
            <th>Note</th>
            <th>angerechnet</th>
        </tr>
        {% for c in courses %}
        <tr>
            <td><a class="studentcourse-detail-link" href="{% url 'studentcourse-detail' c.pk %}">{{ c.course.course_name }}</a></td>
            <td>{{ c.course.credit_points|floatformat }}</td>
            <td>{{ c.course.course_type }}</td>
            <td>{{ c.course.get_specializations_abbreviations }}</td>
            <td>{{ c.semester }}</td>
            <td> {% if c.exam_date %} {{ c.exam_date }} {% else %}k.A.{% endif %}</td>
            <td>{% if c.grade > 0 %}{{ c.grade }} {% else %} k.A. {% endif %}</td>
            <td>{% if c.included %}<i class="fas fa-check"></i> {% else %}<i class="fas fa-times"></i>{% endif %}</td>
        </tr>
        {% endfor %}
    </table>
</div>

studies/master/templates/master/exam_date.html
{% if exam_date and exam_date >= now %} 
    {{ exam_date }}
{% elif exam_date and exam_date < now  %}
    <del>{{ exam_date }}</del> 
{% else %}
    k.A.
{% endif %}

studies/master/templates/master/exam_dates.html
{% extends 'master/base.html' %}
{% block content %}
{% for sem, courses in params %}
<div class="card my-4">
  <h5 class="card-header">{{ sem }}</h5>
  <div class="card-body">
    <div class="table-responsive">
    <table class="table">
        <tr>
            <th>Kursname</th>
            <th>ECTS</th>
            <th>Prüfungstermin</th>
            <th>Note</th>
            <th>angerechnet</th>
        </tr>
        {% for c in courses %}
        <tr>
            <td><a class="studentcourse-detail-link" href="{% url 'studentcourse-detail' c.pk %}">{{ c.course.course_name }}</a></td>
            <td>{{ c.course.credit_points|floatformat }}</td>
            <td> {% include "master/exam_date.html" with exam_date=c.exam_date now=now%}</td>
            <td>{% if c.grade > 0 %}{{ c.grade }} {% else %} k.A. {% endif %}</td>
            <td>{% if c.included %}<i class="fas fa-check"></i> {% else %}<i class="fas fa-times"></i>{% endif %}</td>
        </tr>
        {% endfor %}
    </table>
</div>
  </div>
</div>
{% endfor %}
{% endblock content %}

studies/master/templates/master/login.html
{% extends "master/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Login</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Login</button>
            <small class="text-muted ml-2">
                <a href="#">Passwort vergessen?</a>
            </small>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-mutet">Noch keinen Account? Schreib mir eine Mail!
        </small>
    </div>
</div>
{% endblock content %}

studies/master/templates/master/logout.html
{% extends 'master/base.html' %}
{% block content %}
<h2>Du wurdest abgemeldet.</h2>
<div class="border-top pt-3">
    <small class="text-muted">
        <a href="{% url 'login' %}">Wieder anmelden.</a>
    </small>
</div>
{% endblock content %}

studies/master/templates/master/semester_view.html
{% extends 'master/base.html' %}
{% block content %}
{% for sem, values in params %}
<div class="card my-4">
  <h5 class="card-header">{{ sem }}</h5>
  <div class="card-body">
    <h6 class="card-title">ECTS: {{ values.credits|floatformat }}</h6>
    <h6 class="card-title">Semesterdurchschnitt: {% if values.average > 0 %}{{ values.average }} {% else %} Keine Noten für dieses Semester eingetragen {% endif %}</h6>
    {% include "master/course_table.html" with courses=values.courses %}
  </div>
</div>
{% endfor %}
{% endblock content %}

studies/master/templates/master/studentcourse_confirm_delete.html
{% extends "master/base.html" %} 
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Kurs löschen</legend>
            <h2>Bist du sicher, dass du den Kurs {{ object.course_name }} entfernen willst?</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Ja, entfernen</button>
            <a class="btn btn-outline-secondary" href="{% url 'studentcourse-detail' object.pk %}">Abbrechen</a>
        </div>
    </form>
</div>
{% endblock content %}

studies/master/templates/master/studentcourse_form.html
{% extends "master/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST">
{% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Neue Studienleistung anlegen</legend>
        {{ form|crispy }}
    </fieldset>
        <button class="btn btn-outline-info" type="submit">Speichern</button>
</form>
{{ form.media }}
{% endblock content %}

{% block javascript %}
    <script type="text/javascript">
    // Hack to re-render the course selector if a new course was added
    // listening to on('change') does not work
      let oldLen = 0
      setInterval(() => {
        const newLen = $('#id_course option').length
        if (newLen != oldLen) {
          oldLen = newLen
          $('#id_course').selectpicker('refresh')
        }
      }, 500)
    </script>
{% endblock javascript %}

studies/master/templates/master/usercourse_form.html
{% extends "master/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST">
{% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Neuer Kurs</legend>
        {{ form|crispy }}
    </fieldset>
        <button class="btn btn-outline-info" type="submit">Speichern</button>
</form>
{% endblock content %}